AllCops:
  Exclude:
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'elm-stuff/**/*'
    - 'db/schema.rb'

Metrics/MethodLength:
  Max: 20

Style/FrozenStringLiteralComment:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Metrics/LineLength:
  Enabled: false
